name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 彻底清理 Homebrew 的 tap 问题
      - name: Fix Homebrew
        run: |
          brew untap aws/tap 2>/dev/null || true
          brew tap --force homebrew/core 2>/dev/null || true
          brew update || true

      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Build Package
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lovebypass-deb
          path: ./packages/*.deb
