name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          export THEOS_MAKE_PATH=$THEOS/makefiles
          make clean
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ runner.home }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lovebypass-deb
          path: ./packages/*.deb
